---
openapi: 3.0.0
info:
  title: todo app api
  description: todo app api provides functionalities to add, view, update, and delete your tasks.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/ESLAMNAWARA44_1/todo/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /todo:
    get:
      summary: List all tasks in the todo list
      operationId: getTasks
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/task'
    post:
      summary: Add a new task to the todo list
      operationId: addTask
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/task'
      responses:
        "201":
          description: Task is created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task'
        "400":
          description: Bad request, invalid input
        "409":
          description: Task with the same id already exist
  /todo/{id}:
    get:
      summary: Get task with ID id
      operationId: getTask
      parameters:
      - name: id
        in: path
        description: Task ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          example: 1
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task'
        "400":
          description: Bad request, invalid input
        "404":
          description: Task not found
    delete:
      summary: delete the task with ID id
      operationId: deleteTask
      parameters:
      - name: id
        in: path
        description: Task ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
        "400":
          description: Bad request, invalid input
        "404":
          description: Task not found
    patch:
      summary: toggle completed status
      operationId: CompleteTask
      parameters:
      - name: id
        in: path
        description: Task ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          example: 1
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task'
        "400":
          description: Bad request, invalid input
        "404":
          description: Task not found
  /todo/{id}/{item}:
    patch:
      summary: edit task content
      operationId: updatedTask
      parameters:
      - name: id
        in: path
        description: Task ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          example: 1
      - name: item
        in: path
        description: Task Content
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
          example: clean the room
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task'
        "400":
          description: Bad request, invalid input
        "404":
          description: Task not found
components:
  schemas:
    task:
      required:
      - completed
      - id
      - itemTitle
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        itemTitle:
          type: string
          example: clean the room
        completed:
          type: boolean
          example: false
